// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGGuNOSsyJf99MOP1OpwDu8tPS64WcTI',
    appId: '1:650063797372:web:1df78a5b0ac9ebbe37fdf9',
    messagingSenderId: '650063797372',
    projectId: 'naffco-tools-d722b',
    authDomain: 'naffco-tools-d722b.firebaseapp.com',
    storageBucket: 'naffco-tools-d722b.firebasestorage.app',
    measurementId: 'G-XG8H3WFQGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Rpv0EFE1XLt5ULgIsIsAi-Yvm16t_cM',
    appId: '1:650063797372:android:98bd60a08fa6d70037fdf9',
    messagingSenderId: '650063797372',
    projectId: 'naffco-tools-d722b',
    storageBucket: 'naffco-tools-d722b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGM4DyjhAQ1c2dane34D6dBA0gpnRpsEE',
    appId: '1:650063797372:ios:7ed63b057dc725ae37fdf9',
    messagingSenderId: '650063797372',
    projectId: 'naffco-tools-d722b',
    storageBucket: 'naffco-tools-d722b.firebasestorage.app',
    iosBundleId: 'com.example.naffcoTools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGM4DyjhAQ1c2dane34D6dBA0gpnRpsEE',
    appId: '1:650063797372:ios:7ed63b057dc725ae37fdf9',
    messagingSenderId: '650063797372',
    projectId: 'naffco-tools-d722b',
    storageBucket: 'naffco-tools-d722b.firebasestorage.app',
    iosBundleId: 'com.example.naffcoTools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGGuNOSsyJf99MOP1OpwDu8tPS64WcTI',
    appId: '1:650063797372:web:9f465a2760a8f61b37fdf9',
    messagingSenderId: '650063797372',
    projectId: 'naffco-tools-d722b',
    authDomain: 'naffco-tools-d722b.firebaseapp.com',
    storageBucket: 'naffco-tools-d722b.firebasestorage.app',
    measurementId: 'G-B67CZDYRSX',
  );
}
